# Get Data

In [0]:
import requests
import pandas as pd

In [0]:
url = 'https://raw.githubusercontent.com/MarkIChen/Bank-Customer-Classification-Model/master/Churn_Modelling.csv'
dataset = pd.read_csv(url)

In [3]:
dataset.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [4]:
dataset.shape

(10000, 14)

# Create Training Data

In [0]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [6]:
X.shape, y.shape

((10000, 10), (10000,))

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0])

# Encode dataset

In [8]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

We need to encide contry and gender variables.

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [0]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1]) 

In [0]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2]) 

In [12]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [13]:
X.shape

(10000, 10)

In [0]:
# onehotencoder = OneHotEncoder(categorical_features=[1])
# X = onehotencoder.fit_transform(X).toarray()
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [15]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
X.shape

(10000, 12)

To avoid dumy variable, delete the first col.


In [0]:
X = X[:, 1:]

In [18]:
X.shape

(10000, 11)

# Split data

In [0]:
from sklearn.model_selection import  train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.2,
                                                    random_state = 0
                                                    )

# Feature Scaling

I forgot this process in the beginning, and it will cause bias of the model.

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# Import Library

In [23]:
import tensorflow.keras as keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


# Initializing ANN and Building the model

In [24]:
classifier = Sequential()

In [25]:
X_train.shape

(8000, 11)

In [26]:
# First layer
classifier.add(Dense(6, input_dim = 11, kernel_initializer = 'uniform', activation= 'relu'))
# Second layer
classifier.add(Dense(6, kernel_initializer='uniform', activation='relu'))
# output layer
classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

In [27]:
# apply some algorithms to update the weights in the model
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


# Train the ANN model

In [28]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)




Epoch 1/100





8000/8000 [==============================] - 13s 2ms/step - loss: 0.4863 - acc: 0.7950
Epoch 2/100
8000/8000 [==============================] - 3s 401us/step - loss: 0.4291 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 416us/step - loss: 0.4242 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 3s 418us/step - loss: 0.4204 - acc: 0.8126
Epoch 5/100
8000/8000 [==============================] - 3s 433us/step - loss: 0.4175 - acc: 0.8252
Epoch 6/100
8000/8000 [==============================] - 3s 432us/step - loss: 0.4156 - acc: 0.8262
Epoch 7/100
8000/8000 [==============================] - 3s 407us/step - loss: 0.4142 - acc: 0.8304
Epoch 8/100
8000/8000 [==============================] - 3s 429us/step - loss: 0.4126 - acc: 0.8320
Epoch 9/100
8000/8000 [==============================] - 3s 429us/step - loss: 0.4113 - acc: 0.8320
Epoch 10/100
8000/8000 [==============================] - 4s 444us/step - loss: 0.4101 - acc:

In [0]:
y_pred = classifier.predict(X_test)

In [30]:
X_test

array([[ 1.62776996, -0.57427105, -0.56129438, ...,  0.66011376,
         0.97628121,  1.62185911],
       [-0.61433742, -0.57427105, -1.33847768, ...,  0.66011376,
        -1.02429504,  0.504204  ],
       [-0.61433742,  1.74133801,  0.58347561, ...,  0.66011376,
         0.97628121, -0.41865644],
       ...,
       [-0.61433742,  1.74133801, -0.76084144, ...,  0.66011376,
        -1.02429504,  0.72775202],
       [ 1.62776996, -0.57427105, -0.0046631 , ...,  0.66011376,
         0.97628121, -1.54162886],
       [ 1.62776996, -0.57427105, -0.81335383, ...,  0.66011376,
        -1.02429504,  1.62356528]])

In [31]:
y_pred

array([[0.23028973],
       [0.32763022],
       [0.159444  ],
       ...,
       [0.22177336],
       [0.19776177],
       [0.13804919]], dtype=float32)

In [0]:
y_pred = (y_pred > 0.5)

In [33]:
(y_pred > 0.5)

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1536,   59],
       [ 261,  144]])

In [35]:
# Accuracy
(1568+106)/(1568+27+299+106)

0.837

# Improving the model

The model will have the variance problem if we only test with the test set. To solve this problem, we should introduce the k-fold cross validation.

 ![alt text](https://github.com/MarkIChen/Bank-Customer-Classification-Model/blob/master/img/Screen%20Shot%202020-02-07%20at%2010.47.18%20AM.png?raw=true)

## Import library

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

## define a classifier

In [0]:
def build_classifier():
  classifier = Sequential()
  # First layer
  classifier.add(Dense(6, input_dim = 11, kernel_initializer = 'uniform', activation= 'relu'))
  # Second layer
  classifier.add(Dense(6, kernel_initializer='uniform', activation='relu'))
  # output layer
  classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
  classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
  return classifier

## Create a new classifier with the wrapper

In [0]:
classifier = KerasClassifier(build_fn=build_classifier,
                             batch_size=10, nb_epoch=100)

In [39]:
accuracy = cross_val_score(estimator=classifier,
                           X = X_train,
                           y = y_train,
                           cv = 10
                           )

Epoch 1/1
800/800 [==============================] - 0s 198us/step
Epoch 1/1
800/800 [==============================] - 0s 230us/step
Epoch 1/1
800/800 [==============================] - 0s 242us/step
Epoch 1/1
800/800 [==============================] - 0s 259us/step
Epoch 1/1
800/800 [==============================] - 0s 298us/step
Epoch 1/1
800/800 [==============================] - 0s 303us/step
Epoch 1/1
800/800 [==============================] - 0s 342us/step
Epoch 1/1
800/800 [==============================] - 0s 342us/step
Epoch 1/1
800/800 [==============================] - 0s 457us/step
Epoch 1/1
800/800 [==============================] - 0s 426us/step


In [40]:
accuracy

array([0.78625   , 0.79      , 0.8       , 0.7825    , 0.81625   ,
       0.81      , 0.7875    , 0.79375   , 0.79875   , 0.79624999])

In [41]:
variance = accuracy.std()
mean_accuracy = accuracy.mean()
(variance, mean_accuracy)

(0.010100277584244735, 0.7961249969899655)

## Implement Dropout

To prevent overfitting, we use deopout to avoid one neuron being overtraining."

In [0]:
from keras.layers import Dropout

### Apply dropout to layers.

Every epoch, there will be p percent of neurons being dropped.

In [43]:
classifier = Sequential()
# First layer
classifier.add(Dense(6, input_dim = 11, kernel_initializer = 'uniform', activation= 'relu'))
classifier.add(Dropout(p=0.1))
# Second layer
classifier.add(Dense(6, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(p=0.1))
# output layer
classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  import sys


In [44]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 4s 517us/step - loss: 0.4964 - acc: 0.7950
Epoch 2/100
8000/8000 [==============================] - 3s 396us/step - loss: 0.4371 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 399us/step - loss: 0.4308 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 3s 425us/step - loss: 0.4308 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 3s 388us/step - loss: 0.4318 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 3s 378us/step - loss: 0.4292 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 3s 417us/step - loss: 0.4294 - acc: 0.8069
Epoch 8/100
8000/8000 [==============================] - 3s 406us/step - loss: 0.4293 - acc: 0.8214
Epoch 9/100
8000/8000 [==============================] - 3s 420us/step - loss: 0.4306 - acc: 0.8211
Epoch 10/100
8000/8000 [==============================] - 3s 410us/step - loss: 0.4274 - acc: 0.8244

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
y_pred = (y_pred > 0.5)

In [47]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1565,   30],
       [ 289,  116]])

In [48]:
(1563+115)/(1563+115+32+290)

0.839

## Parameter Tuning

Use different parameters to approach the best performace.

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

In [0]:
def build_customized_classifier(optimizer):
  classifier = Sequential()
  # First layer
  classifier.add(Dense(6, input_dim = 11, kernel_initializer = 'uniform', activation= 'relu'))
  # Second layer
  classifier.add(Dense(6, kernel_initializer='uniform', activation='relu'))
  # output layer
  classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
  classifier.compile(optimizer= optimizer, loss='binary_crossentropy', metrics=['accuracy'])
  return classifier

### Create Classifier

In [0]:
classifier = KerasClassifier(build_fn= build_customized_classifier)

### Create testing paramters

In [0]:
parameters = {'batch_size': [5, 10, 20],
              'nb_epoch': [30, 50, 70],
              'optimizer': ['adam', 'rmsprop']}


### Compile Classifier

In [0]:
grid_search = GridSearchCV(estimator= classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)

In [57]:
grid_search = grid_search.fit(X_train, y_train)

Epoch 1/1
7200/7200 [==============================] - 7s 933us/step - loss: 0.4646 - acc: 0.7971
Epoch 1/1
7200/7200 [==============================] - 6s 858us/step - loss: 0.4648 - acc: 0.7964
Epoch 1/1
7200/7200 [==============================] - 6s 826us/step - loss: 0.4770 - acc: 0.7949
Epoch 1/1
7200/7200 [==============================] - 7s 924us/step - loss: 0.4635 - acc: 0.7975
Epoch 1/1
7200/7200 [==============================] - 7s 917us/step - loss: 0.4712 - acc: 0.7938
Epoch 1/1
7200/7200 [==============================] - 6s 886us/step - loss: 0.4633 - acc: 0.7943
Epoch 1/1
7200/7200 [==============================] - 7s 921us/step - loss: 0.4647 - acc: 0.7969
Epoch 1/1
7200/7200 [==============================] - 6s 881us/step - loss: 0.4629 - acc: 0.7964
Epoch 1/1
7200/7200 [==============================] - 7s 977us/step - loss: 0.4675 - acc: 0.7951
Epoch 1/1
7200/7200 [==============================] - 7s 923us/step - loss: 0.4677 - acc: 0.7960
Epoch 1/1
7200/7200 

In [0]:
best_parameter = grid_search.best_params_
best_accuracy = grid_search.best_score_

In [59]:
best_parameter

{'batch_size': 5, 'nb_epoch': 50, 'optimizer': 'adam'}

In [60]:
best_accuracy

0.797875